// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: shard_snapshots_service.proto

package go_client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ShardSnapshots_Create_FullMethodName  = "/qdrant.ShardSnapshots/Create"
	ShardSnapshots_List_FullMethodName    = "/qdrant.ShardSnapshots/List"
	ShardSnapshots_Delete_FullMethodName  = "/qdrant.ShardSnapshots/Delete"
	ShardSnapshots_Recover_FullMethodName = "/qdrant.ShardSnapshots/Recover"
)

// ShardSnapshotsClient is the client API for ShardSnapshots service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShardSnapshotsClient interface {
	// Create shard snapshot
	Create(ctx context.Context, in *CreateShardSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error)
	// List shard snapshots
	List(ctx context.Context, in *ListShardSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
	// Delete shard snapshot
	Delete(ctx context.Context, in *DeleteShardSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error)
	// Recover shard snapshot
	Recover(ctx context.Context, in *RecoverShardSnapshotRequest, opts ...grpc.CallOption) (*RecoverSnapshotResponse, error)
}

type shardSnapshotsClient struct {
	cc grpc.ClientConnInterface
}

func NewShardSnapshotsClient(cc grpc.ClientConnInterface) ShardSnapshotsClient {
	return &shardSnapshotsClient{cc}
}

func (c *shardSnapshotsClient) Create(ctx context.Context, in *CreateShardSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error) {
	out := new(CreateSnapshotResponse)
	err := c.cc.Invoke(ctx, ShardSnapshots_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardSnapshotsClient) List(ctx context.Context, in *ListShardSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, ShardSnapshots_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardSnapshotsClient) Delete(ctx context.Context, in *DeleteShardSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error) {
	out := new(DeleteSnapshotResponse)
	err := c.cc.Invoke(ctx, ShardSnapshots_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardSnapshotsClient) Recover(ctx context.Context, in *RecoverShardSnapshotRequest, opts ...grpc.CallOption) (*RecoverSnapshotResponse, error) {
	out := new(RecoverSnapshotResponse)
	err := c.cc.Invoke(ctx, ShardSnapshots_Recover_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShardSnapshotsServer is the server API for ShardSnapshots service.
// All implementations must embed UnimplementedShardSnapshotsServer
// for forward compatibility
type ShardSnapshotsServer interface {
	// Create shard snapshot
	Create(context.Context, *CreateShardSnapshotRequest) (*CreateSnapshotResponse, error)
	// List shard snapshots
	List(context.Context, *ListShardSnapshotsRequest) (*ListSnapshotsResponse, error)
	// Delete shard snapshot
	Delete(context.Context, *DeleteShardSnapshotRequest) (*DeleteSnapshotResponse, error)
	// Recover shard snapshot
	Recover(context.Context, *RecoverShardSnapshotRequest) (*RecoverSnapshotResponse, error)
	mustEmbedUnimplementedShardSnapshotsServer()
}

// UnimplementedShardSnapshotsServer must be embedded to have forward compatible implementations.
type UnimplementedShardSnapshotsServer struct {
}

func (UnimplementedShardSnapshotsServer) Create(context.Context, *CreateShardSnapshotRequest) (*CreateSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedShardSnapshotsServer) List(context.Context, *ListShardSnapshotsRequest) (*ListSnapshotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedShardSnapshotsServer) Delete(context.Context, *DeleteShardSnapshotRequest) (*DeleteSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedShardSnapshotsServer) Recover(context.Context, *RecoverShardSnapshotRequest) (*RecoverSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recover not implemented")
}
func (UnimplementedShardSnapshotsServer) mustEmbedUnimplementedShardSnapshotsServer() {}

// UnsafeShardSnapshotsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShardSnapshotsServer will
// result in compilation errors.
type UnsafeShardSnapshotsServer interface {
	mustEmbedUnimplementedShardSnapshotsServer()
}

func RegisterShardSnapshotsServer(s grpc.ServiceRegistrar, srv ShardSnapshotsServer) {
	s.RegisterService(&ShardSnapshots_ServiceDesc, srv)
}

func _ShardSnapshots_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShardSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardSnapshotsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardSnapshots_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardSnapshotsServer).Create(ctx, req.(*CreateShardSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardSnapshots_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShardSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardSnapshotsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardSnapshots_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardSnapshotsServer).List(ctx, req.(*ListShardSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardSnapshots_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShardSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardSnapshotsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardSnapshots_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardSnapshotsServer).Delete(ctx, req.(*DeleteShardSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardSnapshots_Recover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverShardSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardSnapshotsServer).Recover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardSnapshots_Recover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardSnapshotsServer).Recover(ctx, req.(*RecoverShardSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShardSnapshots_ServiceDesc is the grpc.ServiceDesc for ShardSnapshots service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShardSnapshots_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qdrant.ShardSnapshots",
	HandlerType: (*ShardSnapshotsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ShardSnapshots_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ShardSnapshots_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ShardSnapshots_Delete_Handler,
		},
		{
			MethodName: "Recover",
			Handler:    _ShardSnapshots_Recover_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shard_snapshots_service.proto",
}
